### ISSUE TITLE
data used in figSI3_ROC_scRNASeq.R

### ISSUE THREAD

**Issue by SunXQlab** [aristoteleo/Scribe-py#3]
Would you please also share the following datasets that were used in figSI3_ROC_scRNASeq.R? (https://github.com/aristoteleo/Scribe_paper) 
Although the LPS dataset can be downloaded from the GEO database, I find that the format of the data I processed does not match the code. I have also developed a method to infer causal GRN from the cross-sectional data and want to benchmark it with Scribe and other methods. So it will be appreciated that if you can send me the following data as well:

"/Users/xqiu/Dropbox (Cole Trapnell's Lab)/Projects/fstree_ddrtree/RData/analysis_shalek_data.RData"

'./csv_data/LPS_network'

'./csv_data/LPS_subset_network'

'./csv_data/TF_hiearchy.txt'

Thank you so much.

**Comment by Xiaojieqiu** [comment]
I shared the data you asked in the following dropbox link. please find a way to download them. 
https://www.dropbox.com/sh/6uedu8s0qpmag9d/AADqrSdlRZslR7QoLKs3BNjHa?dl=0

Please note that the benchmark on those datasets is not very informative as most of them look pretty much the same. You may need to be more clever in defining a gold standard benchmark dataset

**Comment by Xiaojieqiu** [comment]
@dongbusun I think this issue has been resolved. I will close it now.
